# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rogue
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Pía's website
description: ""
keywords: "Pia Cortes, Pia Cortes-Zuleta, astronomy, astronomer, exoplanets"
url: http://piacortes.github.io
baseurl: ""

google_analytics: UA-126012896-1
repo: http://github.com/piacortes/piacortes.github.io
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Pía Cortés-Zuleta
  job: astronomer
  bio: "PhD student in Astrophysics at the Laboratoire d'Astrophysique de Marseille ([LAM](https://www.lam.fr)) and a LSSTC Data Science fellow. I'm interested in **Exoplanets**, **Data science** applied to astronomy, and projects related to women in science. <br>
      <br> Currently, I'm working on stellar activity characterization of M-dwarfs using optical and near-infrared spectra from SOPHIE and SPIRou.<br>"
  thumb: /images/author.jpg
  email: pia.cortes@lam.fr
  mail4: pia.cortes@lam.fr
  cv: data/cvPCortes.pdf
  url: https://piacortes.github.io
  github: https://github.com/piacortes
  scholar: https://scholar.google.cl/citations?user=3zfydq0AAAAJ&hl=es
  twitter: https://twitter.com/piacortes
  facebook: https://facebook.com/umdevux
  #linkedin: https://linkedin.com/in/nandomoreirame
  #instagram: https://www.instagram.com/pia.cortes
# navbar pages
navbar:
  - slug: about
    title: about
  - slug: data/cvPCortes.pdf
    title: cv
#  - slug: blog
#    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
