baseURL: "https://piacortes.github.io" 
title: Pia's website
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 5 
        - name: Research
          url: research/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 


params:
    description: "This website hosts Pia Cortes Zuleta's information"
    author: Pia Cortes Zuleta
    googleAnalyticsID: "G-SVZD5SZB0C"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about","research"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    socialIcons:
        - name: Email
          url: "mailto:pcz1@st-andrews.ac.uk"
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=3zfydq0AAAAJ&hl=en
        - name: GitHub
          url: https://github.com/piacortes/
        - name: Bluesky
          url: https://bsky.app/profile/piacortes.bsky.social
    profileMode:
          enabled: true
          title: Dr Pia Cortes Zuleta, astronomer
          subtitle: "I am Postdoctoral Research Fellow in Astrophysics at the University of St Andrews, UK. <br> My research focuses on the detection and characterisation of **extrasolar planets**. <br> I am particularly interested in studying the effects of stellar activity on the detection of low-mass planets with the radial velocity technique. <br>" 
          imageUrl: "pia.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About
              url: about/
            - name: Research
              url: research/
            - name: CV
              url: cvPCortesZuleta.pdf
            - name: Papers
              url: papers/
    

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Pia Cortes Zuleta"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2